name: PACS
version: "3.8"

services:
  orthanc:
    image: jodogne/orthanc-python:latest
    container_name: orthanc
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json
      - ./orthanc/db:/var/lib/orthanc/db
      - ./orthanc/worklists:/var/lib/orthanc/worklists
      - ./orthanc/wsi-tiles:/var/lib/orthanc/wsi-tiles
      - ./orthanc/python:/python
      - ./orthanc/plugins:/usr/share/orthanc/plugins
    restart: unless-stopped
    networks:
      - dicom-network

  dicomrouter:
    image: registry.dto.kemkes.go.id/pub/dicom-router:latest
    container_name: dicomrouter
    ports:
      - "11112:11112"   # DICOM
      - "8080:8080"     # Web/API
    environment:
      - AE_TITLE=DCMROUTER
      - ORG_ID=GANTI_DENGAN_ORG_ID_ANDA
      - CLIENT=GANTI_DENGAN_CLIENT_ID_ANDA
      - SECRET=GANTI_DENGAN_SECRET_KEY_ANDA
      - URL=https://api-satusehat.kemkes.go.id
    volumes:
      - ./dicomrouter/data:/app/data
    working_dir: /app
    restart: unless-stopped
    networks:
      - dicom-network

networks:
  dicom-network:
    driver: bridge